export CUDA_VISIBLE_DEVICES=1
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=1.0
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-5 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-5 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0

# python run.py gpus=1 config=timm task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_GC lr=1e-3 optimizer=adam batch_size=64

python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0
