export CUDA_VISIBLE_DEVICES=0,1,2
# python run.py gpus=1 config=timm task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G lr=1e-3 optimizer=adam batch_size=64
# python run.py gpus=1 config=timm task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G lr=1e-3 optimizer=adam batch_size=64 seed=1
# python run.py gpus=1 config=timm task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G lr=1e-3 optimizer=adam batch_size=64 seed=2
# python run.py gpus=1 config=timm task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G lr=1e-3 optimizer=adam batch_size=64 seed=3
# python run.py gpus=1 config=timm task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G lr=1e-3 optimizer=adam batch_size=64 seed=4

# ! MNIST C
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-2 optimizer=sgd batch_size=64
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-2 optimizer=sgd batch_size=64 seed=1
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-2 optimizer=sgd batch_size=64 seed=2
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-2 optimizer=sgd batch_size=64 seed=3
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-2 optimizer=sgd batch_size=64 seed=4

# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt"
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=1
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=2
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=3
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=4

# python run.py gpus=1 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0
# python run.py gpus=1 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=1
# python run.py gpus=1 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=2
# python run.py gpus=1 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=3
# python run.py gpus=1 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=4

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=1
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=2
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=3
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=4

# ! MNIST E
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-2 optimizer=sgd batch_size=64
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-2 optimizer=sgd batch_size=64 seed=1
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-2 optimizer=sgd batch_size=64 seed=2
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-2 optimizer=sgd batch_size=64 seed=3
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-2 optimizer=sgd batch_size=64 seed=4

# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-5 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt"
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-5 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=1
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-5 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=2
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-5 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=3
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-5 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=4

# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0
# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0 seed=1
# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0 seed=2
# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0 seed=3
# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0 seed=4

# python run.py gpus=3 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0
# python run.py gpus=3 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=1
# python run.py gpus=3 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=2
# python run.py gpus=3 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=3
# python run.py gpus=3 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=4


# ! MNIST N
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=5e-3 optimizer=sgd batch_size=64
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=5e-3 optimizer=sgd batch_size=64 seed=1
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=5e-3 optimizer=sgd batch_size=64 seed=2
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=5e-3 optimizer=sgd batch_size=64 seed=3
# python run.py gpus=1 config=dann task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=5e-3 optimizer=sgd batch_size=64 seed=4

# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-6 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt"
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-6 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=1
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-6 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=2
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-6 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=3
# python run.py gpus=1 config=adda task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-6 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" seed=4

# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0
# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0 seed=1
# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0 seed=2
# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0 seed=3
# python run.py gpus=3 config=cycada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=0.0 lambda_sem=0.0 seed=4

python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=1
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=2
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=3
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=50 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem=0.0 seed=4
