export CUDA_VISIBLE_DEVICES=1
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

#! without semantic identity mapping
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_C root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_E root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/FashionMNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/MNIST_N root_tgt=/shared/lorenzo/mnist-zsda/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32


# ! gcada fashionmnist
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_C root_tgt=/root/dezsda/data/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_C root_tgt=/root/dezsda/data/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_C root_tgt=/root/dezsda/data/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_C root_tgt=/root/dezsda/data/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/FashionMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_E root_tgt=/root/dezsda/data/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_E root_tgt=/root/dezsda/data/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_E root_tgt=/root/dezsda/data/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_E root_tgt=/root/dezsda/data/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/FashionMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_N root_tgt=/root/dezsda/data/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_N root_tgt=/root/dezsda/data/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_N root_tgt=/root/dezsda/data/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/EMNIST_N root_tgt=/root/dezsda/data/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.2545.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2592.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2577.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=3 root=/root/dezsda/data/FashionMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/FashionMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=06-task\=digit-val_loss\=0.2706.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
