export CUDA_VISIBLE_DEVICES=2
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# ! without semantic identity mapping
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32


# ! gcada
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32


# ! gcada with sem idt
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0

python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_C root_tgt=/shared/lorenzo/mnist-zsda/MNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0

python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0

python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_E root_tgt=/shared/lorenzo/mnist-zsda/MNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0

python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=1 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/EMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0

python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0297.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=03-task\=digit-val_loss\=0.0226.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.0278.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0
python run.py gpus=1 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/shared/lorenzo/mnist-zsda/MNIST_G root_tgt_train=/shared/lorenzo/mnist-zsda/FashionMNIST_N root_tgt=/shared/lorenzo/mnist-zsda/MNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.0277.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32 lambda_sem_idt=10.0


