set -ex

export CUDA_VISIBLE_DEVICES=1
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=10.0 num_blocks=9 hidden_dim_dsc=32

#! without semantic identity mapping
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=zsgcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 lambda_sem_idt=0.0 num_blocks=9 hidden_dim_dsc=32


# # ! gcada emnist
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_C root_tgt=/root/dezsda/data/EMNIST_C lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_E root_tgt=/root/dezsda/data/EMNIST_E lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/FashionMNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32

# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=04-task\=digit-val_loss\=0.1986.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.1971.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=05-task\=digit-val_loss\=0.2040.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
# python run.py gpus=1 output_num=27 config=gcada task=digit backbone_name=lenet max_epochs=10 root=/root/dezsda/data/EMNIST_G root_tgt_train=/root/dezsda/data/MNIST_N root_tgt=/root/dezsda/data/EMNIST_N lr=1e-4 optimizer=adam batch_size=64 pretrained="/root/dezsda/checkpoints/timm-lenet-epoch\=07-task\=digit-val_loss\=0.2013.ckpt" lambda_idt=1.0 num_blocks=9 hidden_dim_dsc=32
